name:                2captcha
version:             0.1.0.0
github:              "qwbarch/2captcha-haskell"
license:             MIT 
author:              "Edward Yang"
maintainer:          "edwardyang0410@gmail.com"
copyright:           "2021 Edward Yang"
category:            Network
synopsis: Haskell package for easy integration with the 2captcha API. 

description: >
  Haskell package for easy integration with the 2captcha API.  

  Examples: https://github.com/qwbarch/2captcha-haskell/blob/main/app/Main.hs  
  
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- http-client
- wreq
- text
- bytestring
- parsec
- aeson
- lens
- lens-aeson
- exceptions
- clock

default-extensions:
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - UndecidableInstances
  - RankNTypes
  - ScopedTypeVariables
  - LambdaCase
  - MultiParamTypeClasses
  - TemplateHaskell

library:
  source-dirs: src
  ghc-options:
  - -Wall 
  - -Wno-name-shadowing
